# Generated by Django 4.1.4 on 2022-12-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('domain', models.CharField(choices=[('Invoice', 'Invoice'), ('Purchase order', 'Purchase order'), ('Healthcare', 'Healthcare')], max_length=50)),
                ('subdomain', models.CharField(choices=[], max_length=50)),
                ('engine', models.CharField(choices=[('Engine 1', 'Engine 1'), ('Engine 2', 'Engine 2'), ('Engine 3', 'Engine 3')], max_length=50)),
                ('sample', models.FileField(upload_to='pdfs/')),
                ('identifier', models.CharField(max_length=100)),
                ('comments', models.TextField()),
            ],
        ),
    ]
