# Generated by Django 4.1.4 on 2022-12-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_pdf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='subdomain',
        ),
        migrations.AlterField(
            model_name='template',
            name='domain',
            field=models.CharField(choices=[('Invoice', (('Electricity', 'Electricity'), ('Shopping', 'Shopping'))), ('Purchase order', (('PO Subdomain', 'PO Subdomain'),)), ('Healthcare', (('hospital', 'hospital'), ('clinic', 'clinic')))], max_length=50),
        ),
    ]
