# Generated by Django 4.1.4 on 2022-12-23 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_pdf', '0002_remove_template_subdomain_alter_template_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='sample',
        ),
    ]
