# Generated by Django 4.1.4 on 2022-12-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_pdf', '0003_remove_template_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='sample',
            field=models.FileField(default=None, upload_to='pdfs/'),
            preserve_default=False,
        ),
    ]
