# Generated by Django 4.1.4 on 2023-01-09 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_pdf', '0005_alter_template_comments_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fields',
            options={'verbose_name_plural': 'Fields'},
        ),
        migrations.RemoveField(
            model_name='fields',
            name='pdf',
        ),
    ]
