# Generated by Django 4.1.4 on 2023-01-09 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('read_pdf', '0006_alter_fields_options_remove_fields_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='fields',
            name='pdf',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='pdf', to='read_pdf.template'),
            preserve_default=False,
        ),
    ]
