# Generated by Django 4.1.4 on 2023-01-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_pdf', '0008_template_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
