# Generated by Django 4.1.4 on 2023-01-19 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('read_pdf', '0010_alter_template_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution', models.CharField(choices=[('Immediate', 'Immediate'), ('Frequency Based', 'Frequency Based')], max_length=100)),
                ('node', models.CharField(choices=[('Machine 1', 'Machine 1'), ('Machine 2', 'Machine 2'), ('Machine 3', 'Machine 3'), ('Machine 4', 'Machine 4')], max_length=100)),
                ('engine', models.CharField(choices=[('Engine 1', 'Engine 1'), ('Engine 2', 'Engine 2'), ('Engine 3', 'Engine 3')], max_length=100)),
                ('input', models.CharField(choices=[('Network/Local', 'Network/Local'), ('Email', 'Email')], max_length=100)),
                ('file_fields', models.TextField()),
                ('Notification', models.CharField(choices=[('Email', 'Email'), ('SMS', 'SMS'), ('IVR', 'IVR')], max_length=50)),
                ('output_format', models.CharField(choices=[('JSON', 'JSON'), ('EXCEL', 'EXCEL'), ('CSV', 'CSV')], max_length=50)),
                ('output_filename', models.CharField(max_length=100)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='read_pdf.template')),
            ],
        ),
    ]
