# Generated by Django 4.1.4 on 2023-01-19 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_pdf', '0011_job'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job',
            new_name='Jobs',
        ),
        migrations.AlterModelOptions(
            name='jobs',
            options={'verbose_name_plural': 'Jobs'},
        ),
    ]
