# Generated by Django 4.1.4 on 2023-01-25 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('read_pdf', '0012_rename_job_jobs_alter_jobs_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='read_pdf.template'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobs',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
