# Generated by Django 4.1.4 on 2023-03-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_pdf', '0013_jobs_template_alter_jobs_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='Notification',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='engine',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='node',
        ),
        migrations.AlterField(
            model_name='jobs',
            name='input',
            field=models.FileField(upload_to='job_pdfs/'),
        ),
    ]
