# Generated by Django 4.1.4 on 2023-03-01 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_pdf', '0014_remove_jobs_notification_remove_jobs_engine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='execution',
        ),
    ]
