# Generated by Django 4.1.4 on 2023-03-01 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('read_pdf', '0015_remove_jobs_execution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobpdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='job_pdfs')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='read_pdf.jobs')),
            ],
        ),
    ]
