# Generated by Django 4.1.4 on 2023-03-01 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_pdf', '0016_jobpdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='input',
        ),
    ]
