# Generated by Django 4.1.4 on 2023-03-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_pdf', '0018_rename_file_jobpdf_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpdf',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
