# Generated by Django 4.1.4 on 2023-03-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_pdf', '0019_jobpdf_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
