# Generated by Django 4.1.4 on 2023-03-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_pdf', '0021_jobpdf_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fields',
            name='regex_type',
            field=models.CharField(choices=[('Custom', 'Custom'), ('Decimal numbers', 'Decimal numbers'), ('Numeric', 'Numeric'), ('Alphanumeric', 'Alphanumeric'), ('All characters, except newline or line terminator', 'All characters, except newline or line terminator'), ('String beginning with', 'String beginning with'), ('Alphabet', 'Alphabet'), ('Special Characters', 'Special Characters'), ('Alphanumberic with special characters ASCII Characters', 'Alphanumberic with special characters ASCII Characters')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='output_format',
            field=models.CharField(choices=[('JSON', 'JSON'), ('XML', 'XML')], max_length=50),
        ),
        migrations.AlterField(
            model_name='template',
            name='engine',
            field=models.CharField(choices=[('Engine 1', 'Engine 1'), ('Engine 2', 'Engine 2')], max_length=50),
        ),
    ]
